language: php

php:
  - 7.1
  - 7.2

env:
  - PACKAGE_VERSION=high

sudo: false

matrix:
  include:
    - php: 7.1
      env: PACKAGE_VERSION=low
    - php: hhvm
      dist: trusty

before_script:
  - composer selfupdate
  - if [[ "$PACKAGE_VERSION" == "high" ]]; then composer update --prefer-source; fi
  - if [[ "$PACKAGE_VERSION" == "low" ]]; then composer update --prefer-lowest --prefer-source; fi

script: php vendor/bin/phpunit -c tests/phpunit.xml.dist

notifications:
  irc: "irc.freenode.org#jackalope"
