language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  - PACKAGE_VERSION=high

sudo: false

matrix:
  include:
    - php: 5.6
      env: PACKAGE_VERSION=low
    - php: 7.3
      env:
        - PACKAGE_VERSION=high
        - MINIMUM_STABILITY=dev

before_script:
  - composer selfupdate
  - if [[ "$MINIMUM_STABILITY" ]]; then composer config minimum-stability $MINIMUM_STABILITY ; fi
  - if [[ "$PACKAGE_VERSION" == "high" ]]; then composer update --prefer-source; fi
  - if [[ "$PACKAGE_VERSION" == "low" ]]; then composer update --prefer-lowest --prefer-source; fi

script: php vendor/bin/phpunit -c tests/phpunit.xml.dist

notifications:
  irc: "irc.freenode.org#jackalope"
