name: Static analysis

on:
  push:
    branches:
      - '[0-9]+.x'
      - '[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.x'
  pull_request:

jobs:
  phpstan-src:
    name: PHPStan src
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
        with:
          args: analyze --no-progress

  phpstan-tests:
    name: PHPStan tests
    runs-on: ubuntu-latest
    env:
      REQUIRE_DEV: "true"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          composer update --no-progress

      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
        with:
          args: analyze --no-progress -c phpstan.tests.neon.dist
